### ISSUE TITLE
Add login authentication module

### ISSUE THREAD

**Issue by vdubya** [OSAIC/OpenRFA#18]
Minimize friction to account creation. LinkedIn authentication particularly interesting due to professional networking emphasis. Other authentication methods are fine as well, whatever is easiest to implement with an existing Drupal module.

**Comment by jmerlan** [comment]
I tested this module a year ago and it wouldn't work. There have been some updates to Drupal so perhaps it will work now. I'll give it a shot and report back.

**Comment by vdubya** [comment]
Are there other authentication module options?

**Comment by vdubya** [comment]
@jmerlan Maybe you could give this GitHub authentication module a try?
https://www.drupal.org/project/github_connect

**Comment by vdubya** [comment]
I agree that most of our users probably  don’t have a github account but I think we REALLY want to encourage it. Plus if we were able to get github and LinkedIn it would be a really good way to reduce spambots.

**Comment by jmerlan** [comment]
I have the [OneAll module](https://www.drupal.org/project/social_login) that works installed to the dev site. @vdubya, please test it and I can roll it out to the production site. There are several social media sites that it supports, but I've only enable LinkedIn and GitHub for now.

**Comment by vdubya** [comment]
@jmerlan Tested, works and looks fantastic!! Feedback:

1. Might be good to configure using an admin account instead of jmerlan so it looks more official.  (see pic below)
2. Is there a way to merge or associate existing accounts to github/linkedin logins? Also between github and linkedin logins so you didn't have to have two accounts or remember which one you logged in with originally? I could certainly imagine the challenges with that, but 
3. Still requires a password for account creation, is it possible to configure to omit?
4. Minor suggestion to put "(highly recommended)" after "Login with:" and "Instantly register with:" as this would be a very good way for us to cut down on user account creation moderation time. Clearly not flawless but much better than just email verification. Anything we can do to encourage this as the preferred option will help us long term; it is also good to encourage github accounts to encourage open source participation.
5. Verified that it does not allow >1 openrfa account for 1 email address, good!

![2018-10-10 13_51_49-authorize application](https://user-images.githubusercontent.com/6257997/46765947-5ac73c00-cc95-11e8-8e5e-3fd5a815c5bc.png)

**Comment by jmerlan** [comment]
Thanks for the link. I'll set that up. I'm thinking we name it after OSAIC so that it can be the machine account for the entire organization.

**Comment by vdubya** [comment]
Closing because I think it is good for v1 implementation, and we can focus on the account merging/association question as a separate issue. Of course reopen if you disagree!
