### ISSUE TITLE
Migrate Drupal to Github with dev, staging, and production  

### ISSUE THREAD

**Issue by vdubya** [OSAIC/OpenRFA#23]
https://www.drupal.org/node/803746

Also would be good to figure out how to create forks for replicating the site for different collaborative standards development purposes.

**Comment by vdubya** [comment]
Step one is just getting dev separate from production. Discussed using migratable backups as a way to achieve this quickly and easily as a start, or @jmerlan may have some other magic up his sleeve.

**Comment by jmerlan** [comment]
- [ ] Migrate code to dev
- [ ] Migrate DB to dev
- [ ] Enable version control with git

**Comment by jmerlan** [comment]
@vdubya I've gone through the document that you posted and it really is just versioning for the Drupal code, so it doesn't version the database itself. I think we can continue with manual backups using cpanel as I have in the past. I don't think there really is a need to use git with Drupal unless we have custom modules we are developing. Thoughts?

**Comment by jmerlan** [comment]
@vdubya Closing this one out. Please see comment above and reopen if needed.
