### ISSUE TITLE
OpenRFA collaboration vision and framework

### ISSUE THREAD

**Issue by vdubya** [OSAIC/OpenRFA#39]
Per discussion with Andrew Duncan at Arup, this GitHub issue will kickoff the open discussion on OpenRFA vision and framework in order to find common ground for mutually beneficial collaboration.

Andrew, give us a little time to pull together our content and we'll post here to get the conversation rolling.

**Comment by jmerlan** [comment]
I was thinking we start a new repo which includes the vision and framework documents in MD format. Thoughts?

**Comment by vdubya** [comment]
Yes, let's do that. Still think we should keep this issue open to facilitate the discussion and our results to go in the repo. I started the governance repo forked from the Open Data Kit governance repo, so we need to clean that up as well. I think a vision and framework would be smart as a clean start while we iron out the governance details.

**Comment by jmerlan** [comment]
I'm going to close this issue now that we have created an infrastructure repo. Any specific actionable items can be opened either there or on the governance repo. 

Let's try to keep the open-ended discussions on https://discuss.osai.community.
